model_name: 'FNO1D'
num_experts: 100
data_dir: "/vepfs-sha/bx/pde/pdebench/1D/CFD/Train"
batch_size: 16
num_workers: 8
initial_step: 20
t_train: 21
filename: '1D_CFD_Rand_Eta0.01_Zeta0.01_periodic_Train.hdf5'
reduced_resolution: 8
reduced_resolution_t: 5
mom: 0
l2: 0
save_interval: 1
modes: 16
width: 20
num_channel: 3
lr_teacher : 1e-4
batch_train : 16
batch_real : 16
reduced_batch: 1
device: "cuda"
buffer_path: "buffer_1D_CFD"
train_epochs: 30
decay: true

max_experts: 100
max_files: 100
Iteration: 5000   # how many distillation steps to perform
eval_it: 100       # how often to evaluate
epoch_eval_train: 10   # epochs to train a model with synthetic data

sync_num: 1000
grid_size: 
num_t: 21

load_all: Ture  # only use if you can fit all expert trajectories into RAM

max_start_epoch: 25  # max epoch we can start at
expert_epochs: 3

num_eval: 1     # how many networks to evaluate on
syn_steps: 20   # how many steps to take on synthetic data
batch_syn: 8
batch_syn_eval: 24
lr_pde: 1e-03
lr_lr: 1e-05
lr_net: 
syn_data_init: rand
distributed: False