model_name: 'FNO1D'
num_experts: 100
num_workers: 2
data_dir: "data/1DCFD"
batch_size: 100
initial_step: 10
t_train: 100
filename: '1D_CFD_Rand_Eta0.01_Zeta0.01_periodic_Train.hdf5'
reduced_resolution: 8
reduced_resolution_t: 5
mom: 0
l2: 0
save_interval: 10
modes: 16
width: 20
num_channel: 3
lr_teacher : 1e-4
batch_train : 16
batch_real : 16
reduced_batch: 1
device: "cuda"
buffer_path: "buffer_1D_CFD"
train_epochs: 10